INSERT INTO users (name, age) VALUES ("Troy", 26);
INSERT INTO users (name, age) VALUES ("Esther", 28);
INSERT INTO users (name, age) VALUES ("Amira", 24);
INSERT INTO users (name, age) VALUES ("Joel", 26);
INSERT INTO users (name, age) VALUES ("Christina", 31);
INSERT INTO users (name, age) VALUES ("Charles", 35);
INSERT INTO users (name, age) VALUES ("Sadiq", 40);
INSERT INTO users (name, age) VALUES ("Whitney", 31);
INSERT INTO users (name, age) VALUES ("Nana", 28);
INSERT INTO users (name, age) VALUES ("Cynthia", 26);
INSERT INTO users (name, age) VALUES ("Bernice", 27);
INSERT INTO users (name, age) VALUES ("Ernest", 29);
INSERT INTO users (name, age) VALUES ("Mark", 34);
INSERT INTO users (name, age) VALUES ("Edward", 28);
INSERT INTO users (name, age) VALUES ("Samuel", 27);
INSERT INTO users (name, age) VALUES ("Daniel", 24);
INSERT INTO users (name, age) VALUES ("Benjamin", 26);
INSERT INTO users (name, age) VALUES ("Troy", 25);
INSERT INTO users (name, age) VALUES ("Claudia", 23);
INSERT INTO users (name, age) VALUES ("Micah", 20);


INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Crowdfunding", "Business", 1000, "30/01/2020", "04/05/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Climate Change", "Environment", 1500, "01/02/2020", "04/05/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Underground London", "Transportation", 1000, "01/02/2020", "12/09/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Brexit", "Politics", 500, "31/01/2020", "14/02/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("UK Knife", "Criminology", 600, "01/03/2020", "19/10/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ruby", "Software Engineering", 1200, "14/03/2020", "26/07/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Numbers", "Accounting", 200, "14/03/2020", "19/08/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Mona Lisa", "Art", 900, "01/04/2020", "29/09/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Wig Making", "Beauty", 1000, "01/04,2020", "01/07/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Wood", "Carpentry", 900, "01/02/2020", "16,06/2020");


INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 20);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 2, 25);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 3, 19);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (80, 7, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 7, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 8, 30);
INSERT INTO pledges (amount, user_id, project_id) VALUES (260, 9, 29);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 10, 28);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 2, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 22, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (28, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (56, 64, 27);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 5, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 4, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (150, 5, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (80, 7, 11);
INSERT INTO pledges (amount, user_id, project_id) VALUES (500, 8, 26);
INSERT INTO pledges (amount, user_id, project_id) VALUES (140, 7, 24);
INSERT INTO pledges (amount, user_id, project_id) VALUES (90, 8, 21);
INSERT INTO pledges (amount, user_id, project_id) VALUES (70, 9, 22);
INSERT INTO pledges (amount, user_id, project_id) VALUES (85, 7, 20);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 10, 17);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 2, 15);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 6, 14);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 5, 13);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 5, 12);